name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create .env file
        run: |
          echo "NODE_ENV=production" > .env
          echo "PORT=5000" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "AI_PROVIDER=openai" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "CORS_ALLOWED_ORIGINS=https://prompt-enhancer.ai" >> .env
          
      - name: Create frontend environment file
        run: |
          echo "REACT_APP_API_URL=/v1" > frontend/.env.production
          echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" >> frontend/.env.production
          echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" >> frontend/.env
          echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" >> frontend/.env.local