name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install backend dependencies
        run: npm install
        
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          cd ..
        
      - name: Create .env file
        run: |
          echo "NODE_ENV=production" > .env
          echo "PORT=5000" >> .env
          echo "API_KEY=071ab274d796058af0f2c1c205b78009670fc774bd574960" >> .env
          echo "AI_PROVIDER=openai" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "CORS_ALLOWED_ORIGINS=https://prompt-enhancer.ai" >> .env
          echo "TREBLLE_API_KEY=${{ secrets.TREBLLE_API_KEY }}" >> .env
          echo "TREBLLE_PROJECT_ID=${{ secrets.TREBLLE_PROJECT_ID }}" >> .env